[2022-07-07 01:28:43,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.import_to_export scheduled__2022-07-06T04:38:00+00:00 [queued]>
[2022-07-07 01:28:43,531] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: first_dag.import_to_export scheduled__2022-07-06T04:38:00+00:00 [queued]>
[2022-07-07 01:28:43,532] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 01:28:43,533] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-07 01:28:43,533] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 01:28:43,569] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): import_to_export> on 2022-07-06 04:38:00+00:00
[2022-07-07 01:28:43,583] {standard_task_runner.py:52} INFO - Started process 632 to run task
[2022-07-07 01:28:43,586] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: first_dag.import_to_export scheduled__2022-07-06T04:38:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-07-07 01:28:43,587] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: first_dag.import_to_export scheduled__2022-07-06T04:38:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-07-07 01:28:43,588] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'import_to_export', 'scheduled__2022-07-06T04:38:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmp5unwxww8', '--error-file', '/tmp/tmp7efv9__6']
[2022-07-07 01:28:43,590] {standard_task_runner.py:80} INFO - Job 142: Subtask import_to_export
[2022-07-07 01:28:43,590] {local_task_job.py:101} INFO - Task is not able to be run
[2022-07-07 01:28:43,752] {task_command.py:370} INFO - Running <TaskInstance: first_dag.import_to_export scheduled__2022-07-06T04:38:00+00:00 [running]> on host e0840c2a17ac
[2022-07-07 01:28:43,889] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThuyDang
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=import_to_export
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T04:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T04:38:00+00:00
[2022-07-07 01:28:43,903] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/schedule.py", line 10, in import_postgres
    with pd.ExcelFile(file_customer) as xls:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 521, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-07-07 01:28:43,918] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dag, task_id=import_to_export, execution_date=20220706T043800, start_date=20220707T012843, end_date=20220707T012843
[2022-07-07 01:28:43,936] {standard_task_runner.py:97} ERROR - Failed to execute job 142 for task import_to_export (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 632)
[2022-07-07 01:28:43,966] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-07 01:28:44,037] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
